apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw4-docker-deployment   # Название
spec:
  replicas: 1                   # Запуск одной копии приложения
  selector:
    matchLabels:
      app: hw4-docker           # Метка для связи с сервисом
  template:
    metadata:
      labels:
        app: hw4-docker         # Метка, присваиваемая контейнеру
    spec:
      containers:
      - name: hw4-docker-container
        image: items-api:latest  # Имя собранного образа
        ports:
        - containerPort: 8000   # Внутренний порт приложения FastAPI
        
        # НАСТРОЙКА ГРАНИЦ РЕСУРСОВ
        resources:
          limits:
            memory: "256Mi"     # Граница памяти: 256 МБ
            cpu: "500m"         # Граница CPU: 0.5 ядра
          requests:
            memory: "128Mi"
            cpu: "200m"

---
# Описание сетевого сервиса
apiVersion: v1
kind: Service
metadata:
  name: hw4-docker-service
spec:
  selector:
    app: hw4-docker             # Направляет трафик на деплой
  ports:
    - protocol: TCP
      port: 80                  # Внешний порт для доступа
      targetPort: 8000          # Перенаправление на внутренний порт 8000
  type: LoadBalancer            # Создание точки доступа в интернет