version: '3.8'   # Версия формата Docker Compose
name: hw4-docker # Имя проекта

services:
  items_api:
    build:
      context: .                # Текущая директория как контекст сборки
      dockerfile: Dockerfile    # Файл с инструкциями по сборке образа
    container_name: hw4-docker  # Имя запущенного контейнера
    restart: always       # Перезапуск контейнера в случае сбоя
    ports:
      - "8000:8000"       # Маппинг портов: внешний 8000 на внутренний 8000
    volumes:
      - ./data:/app/data  # Связь локальной папки data с папкой в контейнере
    
    # Мониторинг работоспособности приложения
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/items"]
      interval: 30s       # Как часто проверять приложение
      timeout: 5s         # Время ожидания отклика
      retries: 3          # Попытки, после которых статус изменится на unhealthy
    
    # Управление ресурсами (требование задания)
    deploy:
      resources:
        limits:           # Верхний порог потребления (limits)
          cpus: '0.5'     # Ограничение до 0.5 CPU
          memory: 256M    # Ограничение до 256 МБ RAM
        reservations:     # Гарантированный минимум 
          cpus: '0.2'
          memory: 128M